package org.db2.proj2;

public class CountryColumns {
	public static String PLAYER_CAPS_FOR_COUNTRY = "Capital";
	public static String PLAYERS = "Players";
	public static String PLAYER_ASSIST_GOALS = "No_goals";
	public static int PLAYER_ASSIST_GOALS_INDEX = 2;
	public static String PLAYER_ASSIST_ASSISTS = "No_assists";
	public static int PLAYER_ASSIST_ASSISTS_INDEX = 3;
	public static String PLAYER_ID = "Player_id";
	public static int PLAYER_ID_INDEX = 0;
	public static String PLAYER_CARD_NO_OF_YELLOW_CARDS = "No_of_yellow_cards";
	public static int PLAYER_CARD_NO_OF_YELLOW_CARDS_INDEX = 1;
	public static String PLAYER_CARD_NO_OF_RED_CARDS = "No_of_red_cards";
	public static int PLAYER_CARD_NO_OF_RED_CARDS_INDEX = 2;
	public static String PLAYER_LAST_NAME = "Lname";
	public static String PLAYER_FIRST_NAME = "Fname";
	public static String PLAYER_DOB = "Dob";
	public static String PLAYER_HEIGHT = "Height";
	public static String PLAYER_IS_CAPTAIN = "Is_captain";
	public static String PLAYER_POSITION = "Position";
	public static int PLAYER_LAST_NAME_INDEX = 3;
	public static int PLAYER_FIRST_NAME_INDEX = 2;
	public static int PLAYER_DOB_INDEX = 4;
	public static int PLAYER_HEIGHT_INDEX = 6;
	public static int PLAYER_IS_CAPTAIN_INDEX = 10;
	public static int PLAYER_POSITION_INDEX = 8;
	public static String COUNTRY = "Country";
	public static int PLAYER_COUNTRY_INDEX = 5;
	public static String WC_HIST_YEAR = "Year";
	public static String WC_HIST_HOST = "Host";
	public static String WC_HIST_WINNER = "Winner";
	public static int WC_HIST_YEAR_INDEX = 0;
	public static int WC_HIST_HOST_INDEX = 1;
	public static int WC_HIST_WINNER_INDEX = 2;
	public static String COUNTRY_NAME = "Cname";
	public static String COUNTRY_POPULATION = "Population";
	public static String COUNTRY_MANAGER = "Manager";
	public static int COUNTRY_NAME_INDEX = 0;
	public static int COUNTRY_POPULATION_INDEX = 1;
	public static int COUNTRY_MANAGER_INDEX = 3;
	public static int PLAYER_CAPS_FOR_COUNTRY_INDEX = 4;
	public static String HISTORY = "History";
}
